name: hicon_pro_v2
description: Hicon Pro Service App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  image_picker: ^1.0.4
  intl: ^0.18.1

  pdf: ^3.10.7
  printing: ^5.11.0

  share_plus: ^7.2.1
  url_launcher: ^6.2.1

  geolocator: ^10.1.0

flutter:
  uses-material-design: true
